### PR TITLE
Document how to delete a hub

### LINKED ISSUE #354: Delete the Peddie Hub
# Summary

I'm pretty sure that the Peddie Academy hub isn't being used anymore - it hasn't had activity that I've seen, and I emailed the instructor that was going to be testing it out, and he didn't respond. I think that we can delete the hub.

This is the hub: https://github.com/2i2c-org/pilot-hubs/blob/master/hubs.yaml#L311

For reference: [Here are the instructions to delete a hub](https://pilot-hubs.2i2c.org/en/latest/howto/operate/delete-hub.html)

### PR DESCRIPTION
**Pull request by yuvipanda**
Doesn't actually delete any hub, as we discovered
that peddie is still in use

Ref #354

### CODE REVIEW

**Comment by choldgraf** [comment]
whoah hold up a sec! I just checked the Admin panel to be sure that this hub wasn't being used, and this is what I saw:

image

**Comment by choldgraf** [comment]
that actually suggests to me that they have been using the hub quite a lot! Did I totally misinterpret this?

**Comment by yuvipanda** [comment]
@choldgraf actually no, I think that's the correct interpretation. I'll hold off...

**Review by choldgraf — CHANGES_REQUESTED** [review]
We shouldn't merge this! After a closer inspection it turns out that Peddie is using this hub after all (yay! but also phew!). Let's change this PR to just be a docs improvement and not remove the Peddie config

**Comment by yuvipanda** [comment]
@choldgraf done!

**Pull request merged**
