### PR TITLE
Don't explicitly generate proxy.secretToken

### PR DESCRIPTION
**Pull request by yuvipanda**
Thanks to
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1993,
proxy.secretToken is automatically generated :)

### CODE REVIEW

**Comment by damianavila** [comment]
@yuvipanda, do you know if this was this already released?

**Comment by yuvipanda** [comment]
Yep!

**Comment by damianavila** [comment]
Accordingly to this page: https://jupyterhub.github.io/helm-chart/
0.11.1 was released on Jan 15 and the reference PR was merged on Jan 27.
What am I missing here?

**Comment by yuvipanda** [comment]
@damianavila ah, so I like running closer to master :D If you look at `hub-templates/basehub/Chart.yaml`, you'll see that we're actually on `0.11.1-n277.h61b0e003`, which was released on March 3 (according to https://jupyterhub.github.io/helm-chart/). It was updated last in f51325e6c355892842e8ac1ac464c8624690ecea, to bring in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2077 (which I consider a very critical fix).

**Comment by damianavila** [comment]
> ah, so I like running closer to master :D

Ah, so you like to run at the cutting edge 😛 
Thanks for the clarification!

**Review by damianavila — APPROVED** [review]
LGTM now!

**Comment by yuvipanda** [comment]
@damianavila Thanks :D More so than cutting edge, I think z2jh master is pretty stable, and we should find resources to help make releases more frequently - see https://github.com/jupyterhub/team-compass/issues/384 and https://github.com/2i2c-org/pilot-hubs/issues/233

**Pull request merged**
