### PR TITLE
Provision a separate nodepool for ohw

### PR DESCRIPTION
**Pull request by yuvipanda**
- Helps provide dedicated resources for the hackathon
- Lays the groundwork for keeping a warm pool of nodes for
  the hackathon.
- Uses n1- machines rather than e2- machines. We should move
  everything to n1 - the sustained use discount is worth a
  lot of money
- Put ohw notebook and dask pods on the new node pool
- Enable continuous image prepuller, so new nodes coming up
   will automatically pull the image. The notebook image tag is also
   explicitly set so the pre-puller can bring it in.

Ref https://github.com/2i2c-org/pilot-hubs/issues/549

### CODE REVIEW

**Comment by yuvipanda** [comment]
I've already deployed this, as the hackathon is happening shortly.`terraform apply` output:

```
❯ terraform apply -var-file projects/pilot-hubs.tfvars                                                                                1 ↵
Acquiring state lock. This may take a few moments...
google_artifact_registry_repository.registry: Refreshing state... [id=projects/two-eye-two-see/locations/us-central1/repositories/pilot-hubs-registry]
google_service_account.cluster_sa: Refreshing state... [id=projects/two-eye-two-see/serviceAccounts/pilot-hubs-cluster-sa@two-eye-two-see.iam.gserviceaccount.com]
google_project_iam_custom_role.identify_project_role: Refreshing state... [id=projects/two-eye-two-see/roles/pilot_hubs_user_sa_role]
google_service_account.cd_sa: Refreshing state... [id=projects/two-eye-two-see/serviceAccounts/pilot-hubs-cd-sa@two-eye-two-see.iam.gserviceaccount.com]
google_project_iam_member.cluster_sa_roles["roles/monitoring.viewer"]: Refreshing state... [id=two-eye-two-see/roles/monitoring.viewer/serviceaccount:pilot-hubs-cluster-sa@two-eye-two-see.iam.gserviceaccount.com]
google_project_iam_member.cluster_sa_roles["roles/logging.logWriter"]: Refreshing state... [id=two-eye-two-see/roles/logging.logWriter/serviceaccount:pilot-hubs-cluster-sa@two-eye-two-see.iam.gserviceaccount.com]
google_project_iam_member.cluster_sa_roles["roles/monitoring.metricWriter"]: Refreshing state... [id=two-eye-two-see/roles/monitoring.metricWriter/serviceaccount:pilot-hubs-cluster-sa@two-eye-two-see.iam.gserviceaccount.com]
google_project_iam_member.cluster_sa_roles["roles/artifactregistry.reader"]: Refreshing state... [id=two-eye-two-see/roles/artifactregistry.reader/serviceaccount:pilot-hubs-cluster-sa@two-eye-two-see.iam.gserviceaccount.com]
google_project_iam_member.cluster_sa_roles["roles/stackdriver.resourceMetadata.writer"]: Refreshing state... [id=two-eye-two-see/roles/stackdriver.resourceMetadata.writer/serviceaccount:pilot-hubs-cluster-sa@two-eye-two-see.iam.gserviceaccount.com]
google_project_iam_member.cd_sa_roles["roles/artifactregistry.writer"]: Refreshing state... [id=two-eye-two-see/roles/artifactregistry.writer/serviceaccount:pilot-hubs-cd-sa@two-eye-two-see.iam.gserviceaccount.com]
google_project_iam_member.cd_sa_roles["roles/container.admin"]: Refreshing state... [id=two-eye-two-see/roles/container.admin/serviceaccount:pilot-hubs-cd-sa@two-eye-two-see.iam.gserviceaccount.com]
google_service_account_key.cd_sa: Refreshing state... [id=projects/two-eye-two-see/serviceAccounts/pilot-hubs-cd-sa@two-eye-two-see.iam.gserviceaccount.com/keys/d163d304874c5f2e2b83b20b85782ea82f49af8d]
google_container_cluster.cluster: Refreshing state... [id=projects/two-eye-two-see/locations/us-central1-b/clusters/pilot-hubs-cluster]
google_project_iam_member.identify_project_binding: Refreshing state... [id=two-eye-two-see/projects/two-eye-two-see/roles/pilot_hubs_user_sa_role/serviceaccount:pilot-hubs-cluster-sa@two-eye-two-see.iam.gserviceaccount.com]
google_container_node_pool.notebook["user"]: Refreshing state... [id=projects/two-eye-two-see/locations/us-central1-b/clusters/pilot-hubs-cluster/nodePools/nb-user]
google_container_node_pool.core: Refreshing state... [id=projects/two-eye-two-see/locations/us-central1-b/clusters/pilot-hubs-cluster/nodePools/core-pool]
google_container_node_pool.dask_worker["worker"]: Refreshing state... [id=projects/two-eye-two-see/locations/us-central1-b/clusters/pilot-hubs-cluster/nodePools/dask-worker]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # google_project_iam_member.identify_project_binding has been changed
  ~ resource "google_project_iam_member" "identify_project_binding" {
      ~ etag    = "BwXEPhQPuM4=" -> "BwXGD1kHuAc="
        id      = "two-eye-two-see/projects/two-eye-two-see/roles/pilot_hubs_user_sa_role/serviceaccount:pilot-hubs-cluster-sa@two-eye-two-see.iam.gserviceaccount.com"
        # (3 unchanged attributes hidden)
    }
  # google_project_iam_member.cd_sa_roles["roles/artifactregistry.writer"] has been changed
  ~ resource "google_project_iam_member" "cd_sa_roles" {
      ~ etag    = "BwXEPhQPuM4=" -> "BwXGD1kHuAc="
        id      = "two-eye-two-see/roles/artifactregistry.writer/serviceaccount:pilot-hubs-cd-sa@two-eye-two-see.iam.gserviceaccount.com"
        # (3 unchanged attributes hidden)
    }
  # google_project_iam_member.cd_sa_roles["roles/container.admin"] has been changed
  ~ resource "google_project_iam_member" "cd_sa_roles" {
      ~ etag    = "BwXEPhQPuM4=" -> "BwXGD1kHuAc="
        id      = "two-eye-two-see/roles/container.admin/serviceaccount:pilot-hubs-cd-sa@two-eye-two-see.iam.gserviceaccount.com"
        # (3 unchanged attributes hidden)
    }
  # google_container_cluster.cluster has been changed
  ~ resource "google_container_cluster" "cluster" {
        id                          = "projects/two-eye-two-see/locations/us-central1-b/clusters/pilot-hubs-cluster"
      ~ instance_group_urls         = [
            "https://www.googleapis.com/compute/beta/projects/two-eye-two-see/zones/us-central1-b/instanceGroups/gke-pilot-hubs-cluster-core-pool-d184c825-grp",
          + "https://www.googleapis.com/compute/beta/projects/two-eye-two-see/zones/us-central1-b/instanceGroups/gke-pilot-hubs-cluster-nb-user-b2611a2c-grp",
          + "https://www.googleapis.com/compute/beta/projects/two-eye-two-see/zones/us-central1-b/instanceGroups/gke-pilot-hubs-cluster-dask-worker-771e97b1-grp",
        ]
        name                        = "pilot-hubs-cluster"
        # (26 unchanged attributes hidden)









      + node_pool {
          + initial_node_count  = 0
          + instance_group_urls = [
              + "https://www.googleapis.com/compute/v1/projects/two-eye-two-see/zones/us-central1-b/instanceGroupManagers/gke-pilot-hubs-cluster-nb-user-b2611a2c-grp",
            ]
          + max_pods_per_node   = 0
          + name                = "nb-user"
          + node_count          = 1
          + node_locations      = [
              + "us-central1-b",
            ]
          + version             = "1.19.9-gke.1900"

          + autoscaling {
              + max_node_count = 20
              + min_node_count = 0
            }

          + management {
              + auto_repair  = true
              + auto_upgrade = false
            }

          + node_config {
              + disk_size_gb      = 100
              + disk_type         = "pd-standard"
              + guest_accelerator = []
              + image_type        = "COS_CONTAINERD"
              + labels            = {
                  + "hub.jupyter.org/node-purpose" = "user"
                  + "k8s.dask.org/node-purpose"    = "scheduler"
                }
              + local_ssd_count   = 0
              + machine_type      = "e2-highmem-4"
              + metadata          = {
                  + "disable-legacy-endpoints" = "true"
                }
              + oauth_scopes      = [
                  + "https://www.googleapis.com/auth/cloud-platform",
                ]
              + preemptible       = false
              + service_account   = "pilot-hubs-cluster-sa@two-eye-two-see.iam.gserviceaccount.com"
              + tags              = []
              + taint             = [
                  + {
                      + effect = "NO_SCHEDULE"
                      + key    = "hub.jupyter.org_dedicated"
                      + value  = "user"
                    },
                ]

              + shielded_instance_config {
                  + enable_integrity_monitoring = true
                  + enable_secure_boot          = false
                }

              + workload_metadata_config {
                  + node_metadata = "GKE_METADATA_SERVER"
                }
            }

          + upgrade_settings {
              + max_surge       = 1
              + max_unavailable = 0
            }
        }
      + node_pool {
          + initial_node_count  = 0
          + instance_group_urls = [
              + "https://www.googleapis.com/compute/v1/projects/two-eye-two-see/zones/us-central1-b/instanceGroupManagers/gke-pilot-hubs-cluster-dask-worker-771e97b1-grp",
            ]
          + max_pods_per_node   = 0
          + name                = "dask-worker"
          + node_count          = 0
          + node_locations      = [
              + "us-central1-b",
            ]
          + version             = "1.19.9-gke.1900"

          + autoscaling {
              + max_node_count = 100
              + min_node_count = 0
            }

          + management {
              + auto_repair  = true
              + auto_upgrade = false
            }

          + node_config {
              + disk_size_gb      = 100
              + disk_type         = "pd-ssd"
              + guest_accelerator = []
              + image_type        = "COS_CONTAINERD"
              + labels            = {
                  + "k8s.dask.org/node-purpose" = "worker"
                }
              + local_ssd_count   = 0
              + machine_type      = "e2-highmem-4"
              + metadata          = {
                  + "disable-legacy-endpoints" = "true"
                }
              + oauth_scopes      = [
                  + "https://www.googleapis.com/auth/cloud-platform",
                ]
              + preemptible       = true
              + service_account   = "pilot-hubs-cluster-sa@two-eye-two-see.iam.gserviceaccount.com"
              + tags              = []
              + taint             = [
                  + {
                      + effect = "NO_SCHEDULE"
                      + key    = "k8s.dask.org_dedicated"
                      + value  = "worker"
                    },
                ]

              + shielded_instance_config {
                  + enable_integrity_monitoring = true
                  + enable_secure_boot          = false
                }

              + workload_metadata_config {
                  + node_metadata = "GKE_METADATA_SERVER"
                }
            }

          + upgrade_settings {
              + max_surge       = 1
              + max_unavailable = 0
            }
        }




        # (13 unchanged blocks hidden)
    }
  # google_container_node_pool.dask_worker["worker"] has been changed
  ~ resource "google_container_node_pool" "dask_worker" {
        id                  = "projects/two-eye-two-see/locations/us-central1-b/clusters/pilot-hubs-cluster/nodePools/dask-worker"
        name                = "dask-worker"
        # (8 unchanged attributes hidden)



      ~ node_config {
          + tags              = []
            # (12 unchanged attributes hidden)


            # (2 unchanged blocks hidden)
        }

        # (3 unchanged blocks hidden)
    }
  # google_container_node_pool.notebook["user"] has been changed
  ~ resource "google_container_node_pool" "notebook" {
        id                  = "projects/two-eye-two-see/locations/us-central1-b/clusters/pilot-hubs-cluster/nodePools/nb-user"
        name                = "nb-user"
      ~ node_count          = 0 -> 1
        # (7 unchanged attributes hidden)



      ~ node_config {
          + tags              = []
            # (12 unchanged attributes hidden)


            # (2 unchanged blocks hidden)
        }

        # (3 unchanged blocks hidden)
    }
  # google_project_iam_member.cluster_sa_roles["roles/stackdriver.resourceMetadata.writer"] has been changed
  ~ resource "google_project_iam_member" "cluster_sa_roles" {
      ~ etag    = "BwXEPhQPuM4=" -> "BwXGD1kHuAc="
        id      = "two-eye-two-see/roles/stackdriver.resourceMetadata.writer/serviceaccount:pilot-hubs-cluster-sa@two-eye-two-see.iam.gserviceaccount.com"
        # (3 unchanged attributes hidden)
    }
  # google_project_iam_member.cluster_sa_roles["roles/artifactregistry.reader"] has been changed
  ~ resource "google_project_iam_member" "cluster_sa_roles" {
      ~ etag    = "BwXEPhQPuM4=" -> "BwXGD1kHuAc="
        id      = "two-eye-two-see/roles/artifactregistry.reader/serviceaccount:pilot-hubs-cluster-sa@two-eye-two-see.iam.gserviceaccount.com"
        # (3 unchanged attributes hidden)
    }
  # google_project_iam_member.cluster_sa_roles["roles/logging.logWriter"] has been changed
  ~ resource "google_project_iam_member" "cluster_sa_roles" {
      ~ etag    = "BwXEPhQPuM4=" -> "BwXGD1kHuAc="
        id      = "two-eye-two-see/roles/logging.logWriter/serviceaccount:pilot-hubs-cluster-sa@two-eye-two-see.iam.gserviceaccount.com"
        # (3 unchanged attributes hidden)
    }
  # google_project_iam_member.cluster_sa_roles["roles/monitoring.metricWriter"] has been changed
  ~ resource "google_project_iam_member" "cluster_sa_roles" {
      ~ etag    = "BwXEPhQPuM4=" -> "BwXGD1kHuAc="
        id      = "two-eye-two-see/roles/monitoring.metricWriter/serviceaccount:pilot-hubs-cluster-sa@two-eye-two-see.iam.gserviceaccount.com"
        # (3 unchanged attributes hidden)
    }
  # google_project_iam_member.cluster_sa_roles["roles/monitoring.viewer"] has been changed
  ~ resource "google_project_iam_member" "cluster_sa_roles" {
      ~ etag    = "BwXEPhQPuM4=" -> "BwXGD1kHuAc="
        id      = "two-eye-two-see/roles/monitoring.viewer/serviceaccount:pilot-hubs-cluster-sa@two-eye-two-see.iam.gserviceaccount.com"
        # (3 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following
plan may include actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  # google_container_node_pool.dask_worker["ohw"] will be created
  + resource "google_container_node_pool" "dask_worker" {
      + cluster             = "pilot-hubs-cluster"
      + id                  = (known after apply)
      + initial_node_count  = 0
      + instance_group_urls = (known after apply)
      + location            = "us-central1-b"
      + max_pods_per_node   = (known after apply)
      + name                = "dask-ohw"
      + name_prefix         = (known after apply)
      + node_count          = (known after apply)
      + node_locations      = (known after apply)
      + operation           = (known after apply)
      + project             = "two-eye-two-see"
      + version             = (known after apply)

      + autoscaling {
          + max_node_count = 100
          + min_node_count = 0
        }

      + management {
          + auto_repair  = true
          + auto_upgrade = false
        }

      + node_config {
          + disk_size_gb      = (known after apply)
          + disk_type         = "pd-ssd"
          + guest_accelerator = (known after apply)
          + image_type        = (known after apply)
          + labels            = {
              + "2i2c.org/community"        = "ohw"
              + "k8s.dask.org/node-purpose" = "worker"
            }
          + local_ssd_count   = (known after apply)
          + machine_type      = "n1-highmem-4"
          + metadata          = (known after apply)
          + oauth_scopes      = [
              + "https://www.googleapis.com/auth/cloud-platform",
            ]
          + preemptible       = true
          + service_account   = "pilot-hubs-cluster-sa@two-eye-two-see.iam.gserviceaccount.com"
          + taint             = [
              + {
                  + effect = "NO_SCHEDULE"
                  + key    = "k8s.dask.org_dedicated"
                  + value  = "worker"
                },
            ]

          + shielded_instance_config {
              + enable_integrity_monitoring = (known after apply)
              + enable_secure_boot          = (known after apply)
            }

          + workload_metadata_config {
              + node_metadata = "GKE_METADATA_SERVER"
            }
        }

      + upgrade_settings {
          + max_surge       = (known after apply)
          + max_unavailable = (known after apply)
        }
    }

  # google_container_node_pool.notebook["ohw"] will be created
  + resource "google_container_node_pool" "notebook" {
      + cluster             = "pilot-hubs-cluster"
      + id                  = (known after apply)
      + initial_node_count  = 0
      + instance_group_urls = (known after apply)
      + location            = "us-central1-b"
      + max_pods_per_node   = (known after apply)
      + name                = "nb-ohw"
      + name_prefix         = (known after apply)
      + node_count          = (known after apply)
      + node_locations      = (known after apply)
      + operation           = (known after apply)
      + project             = "two-eye-two-see"
      + version             = (known after apply)

      + autoscaling {
          + max_node_count = 50
          + min_node_count = 0
        }

      + management {
          + auto_repair  = true
          + auto_upgrade = false
        }

      + node_config {
          + disk_size_gb      = (known after apply)
          + disk_type         = (known after apply)
          + guest_accelerator = (known after apply)
          + image_type        = (known after apply)
          + labels            = {
              + "2i2c.org/community"           = "ohw"
              + "hub.jupyter.org/node-purpose" = "user"
              + "k8s.dask.org/node-purpose"    = "scheduler"
            }
          + local_ssd_count   = (known after apply)
          + machine_type      = "n1-highmem-4"
          + metadata          = (known after apply)
          + oauth_scopes      = [
              + "https://www.googleapis.com/auth/cloud-platform",
            ]
          + preemptible       = false
          + service_account   = "pilot-hubs-cluster-sa@two-eye-two-see.iam.gserviceaccount.com"
          + taint             = [
              + {
                  + effect = "NO_SCHEDULE"
                  + key    = "hub.jupyter.org_dedicated"
                  + value  = "user"
                },
            ]

          + shielded_instance_config {
              + enable_integrity_monitoring = (known after apply)
              + enable_secure_boot          = (known after apply)
            }

          + workload_metadata_config {
              + node_metadata = "GKE_METADATA_SERVER"
            }
        }

      + upgrade_settings {
          + max_surge       = (known after apply)
          + max_unavailable = (known after apply)
        }
    }

  # google_project_iam_custom_role.identify_project_role will be updated in-place
  ~ resource "google_project_iam_custom_role" "identify_project_role" {
      ~ description = "A description" -> "Minimal role for hub users on pilot-hubs to identify as current project"
        id          = "projects/two-eye-two-see/roles/pilot_hubs_user_sa_role"
        name        = "projects/two-eye-two-see/roles/pilot_hubs_user_sa_role"
        # (6 unchanged attributes hidden)
    }

Plan: 2 to add, 1 to change, 0 to destroy.

Do you want to perform these actions in workspace "pilot-hubs"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

google_project_iam_custom_role.identify_project_role: Modifying... [id=projects/two-eye-two-see/roles/pilot_hubs_user_sa_role]
google_container_node_pool.notebook["ohw"]: Creating...
google_container_node_pool.dask_worker["ohw"]: Creating...
google_project_iam_custom_role.identify_project_role: Modifications complete after 2s [id=projects/two-eye-two-see/roles/pilot_hubs_user_sa_role]
google_container_node_pool.dask_worker["ohw"]: Still creating... [10s elapsed]
google_container_node_pool.notebook["ohw"]: Still creating... [10s elapsed]
google_container_node_pool.notebook["ohw"]: Still creating... [20s elapsed]
google_container_node_pool.dask_worker["ohw"]: Still creating... [20s elapsed]
google_container_node_pool.dask_worker["ohw"]: Still creating... [30s elapsed]
google_container_node_pool.notebook["ohw"]: Still creating... [30s elapsed]
google_container_node_pool.notebook["ohw"]: Creation complete after 35s [id=projects/two-eye-two-see/locations/us-central1-b/clusters/pilot-hubs-cluster/nodePools/nb-ohw]
google_container_node_pool.dask_worker["ohw"]: Still creating... [40s elapsed]
google_container_node_pool.dask_worker["ohw"]: Still creating... [50s elapsed]
google_container_node_pool.dask_worker["ohw"]: Still creating... [1m0s elapsed]
google_container_node_pool.dask_worker["ohw"]: Creation complete after 1m9s [id=projects/two-eye-two-see/locations/us-central1-b/clusters/pilot-hubs-cluster/nodePools/dask-ohw]
Releasing state lock. This may take a few moments...

Apply complete! Resources: 2 added, 1 changed, 0 destroyed.

Outputs:

ci_deployer_key = <sensitive>
```

**Comment by yuvipanda** [comment]
The unrelated empty changes around `tags` are being fixed by @sgibson in #538

**Comment by choldgraf** [comment]
Is this something that were special casing for this hub? Or something we're prototyping as standard practice for event based hubs?

**Comment by yuvipanda** [comment]
@choldgraf I think this should be standard practice for event based hubs that are not just using small datasets. An outcome of the ohw hub should be a checklist for event based hubs.

**Comment by yuvipanda** [comment]
I'm going to merge this now - if any other PR gets merged in the repo, the changes here in this PR  (already deployed) will be undone.

**Comment by damianavila** [comment]
Looking quickly at the PR content, I like this idea!
Having separated/dedicated nodepools for specific hubs (with specific and maybe temporal requirements) in the same cluster makes sense to me.
Wondering if we can eventually find some common subsets of nodepools so we do not have hub-specific names in the terraform file and we somehow config/map the hubs to those common buckets depending on their requirements...

**Pull request merged**
