### PR TITLE
Use latest pangeo docker image for staging

### PR DESCRIPTION
**Pull request by rabernat**
Cartopy is broken in the tag we are pointing to. Should be fixed in this one.

I hope this is the correct way to propose this update. 🙏

### CODE REVIEW

**Comment by sgibson91** [comment]
Thanks @rabernat! I'm happy to merge this, but for future reference it is possible to change the image using the configurator https://pilot.2i2c.org/en/latest/admin/howto/configurator.html The image set in the configurator will always override what is in the config, so we don't cause a bottle neck for you :)

**Review by sgibson91 — APPROVED** [review]

**Comment by rabernat** [comment]
In other words, RTFM! 🙃  Thanks Sarah.

**Comment by sgibson91** [comment]
Hub health check failed when I merged this but the helm upgrade succeeded so I expect that was just test flakiness. Do holler in `#hub-support` on Slack though if something doesn't seem right

**Comment by rabernat** [comment]
So I screwed up and pointed to a tag that exists in GitHub but not docker! 🤦 

Let's just revert this and I will use the admin console.

**Pull request merged**
