### PR TITLE
Run deploy actions only when necessary

### PR DESCRIPTION
**Pull request by yuvipanda**

### CODE REVIEW

**Review by sgibson91 — APPROVED** [review]
LGTM!

**Comment by damianavila** [comment]
What about changes in the images/user?

**Comment by yuvipanda** [comment]
> What about changes in the images/user?

Those need to be manually built and deployed - there's no autobuilding yet.

**Comment by damianavila** [comment]
> Those need to be manually built and deployed - there's no autobuilding yet.

Yep, you are right... I was thinking about the tag change but that actually happens in the hub template, IIRC.

**Review by damianavila — APPROVED** [review]
LGTM

**Comment by yuvipanda** [comment]
Thanks, @damianavila

**Pull request merged**
