### PR TITLE
Add UToronto to list of running hubs

### PR DESCRIPTION
**Pull request by yuvipanda**
Ref #175

### CODE REVIEW

**Comment by choldgraf** [comment]
We do keep track of this here: https://team-compass.2i2c.org/en/latest/reference/hubs.html

I imagined that this list was *just* for the pilot hubs repository, and the list in the team compass would be for all hub infrastructure across repositories. Do you think there's a better way to structure that?

**Comment by yuvipanda** [comment]
Ah, I didn't know of that one. I'd like them all to be in one place though - mostly as a way to show people 'here is all the hubs we run', regardless of location of repository.

**Comment by choldgraf** [comment]
Well yes that was the goal of https://team-compass.2i2c.org/en/latest/reference/hubs.html :-)

It used to have the table from this repository as well, but we moved it here because it was brittle having a table in one repo that used data from another repo.

Another option would be to move everything in that page to the docs for this repo, I just want sure if that would confuse things

**Comment by yuvipanda** [comment]
> Another option would be to move everything in that page to the docs for this repo, I just want sure if that would confuse things

I like that :)

Once #368 is done we'll archive the pangeo-hubs repo as well, so that entry would be gone too.

**Comment by choldgraf** [comment]
Ok cool so then I think the order of operations is:

1. Add the extra hub repos to the list here (we should make clear that those are hosted at a different repo somehow)
2. Remove from team compass and link to these docs from the TC page

**Comment by yuvipanda** [comment]
Ok, done

image

I don't want to add pangeo-hubs repo here - Farallon is already listed here.

**Comment by choldgraf** [comment]
Nice! Do you wanna just leave the Pangeo hubs in the team compass table? I was imagining we'd just remove that table entirely and point here...

**Comment by yuvipanda** [comment]
Yeah, I was thinking we'll remove that table entirely too. I'll do a PR there later

**Comment by choldgraf** [comment]
But then won't we not have any record of the pangeo hubs repo existing? Or do you plan to delete that super quickly?

**Comment by yuvipanda** [comment]
@choldgraf yeah, no new work can happen there now anyway. I'm tempted to archive it already...

**Comment by yuvipanda** [comment]
@choldgraf I opened https://github.com/2i2c-org/team-compass/pull/103, but also left a comment there about utoronto hub

**Review by choldgraf — APPROVED** [review]
Sounds good!

**Review by damianavila — APPROVED** [review]
LGTM, merging now.

**Pull request merged**
