### PR TITLE
Built terraform reference docs with ReadTheDocs

### PR DESCRIPTION
**Pull request by yuvipanda**

### CODE REVIEW

**Comment by damianavila** [comment]
@yuvipanda, when I check for the first link in the terraform reference section I see something like this:

Screen Shot 2021-06-24 at 16 11 51

Btw, it is happening for some of the links, not all of them...

**Comment by yuvipanda** [comment]
@damianavila yeah, it looks like whatever convention terraform-docs is expecting the google provider to follow, it isn't following.

As an example, it expects docs for project_iam_member to be at  https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/project_iam_member but it's actually at https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_iam...

**Comment by yuvipanda** [comment]
I've now removed the 'resources' section

**Comment by damianavila** [comment]
> @damianavila yeah, it looks like whatever convention terraform-docs is expecting the google provider to follow, it isn't following.

Mmm... bummer...

> I've now removed the 'resources' section

I liked that section, but I think the removal is the way forward...

**Review by damianavila — APPROVED** [review]

**Review by sgibson91 — APPROVED** [review]
LGTM!

**Comment by yuvipanda** [comment]
Thanks, @sgibson91!

**Pull request merged**
